@GolosaTgBotApi_HostAddress = http://localhost:5000

POST {{GolosaTgBotApi_HostAddress}}/api/post
Content-Type: application/json
Accept: application/json
{
    "limit": 5,
    "offset": 0
}
###
POST {{GolosaTgBotApi_HostAddress}}/api/comment/post
Content-Type: application/json
Accept: application/json
{
    "postId": 3,
    "limit": 5,
    "offset": 0
}
###
GET {{GolosaTgBotApi_HostAddress}}/api/post/3
Content-Type: application/json
Accept: application/json
###
GET {{GolosaTgBotApi_HostAddress}}/api/test
Accept: application/json
###
